{
  crops:
    [
      { position: 0, enable: true, title: "sunflower", sell: true },
      { position: 1, enable: true, title: "potato", sell: true },
      { position: 2, enable: true, title: "pumpkin", sell: true },
      { position: 3, enable: true, title: "carrot", sell: true },
      { position: 4, enable: true, title: "cabbage", sell: true },
      { position: 5, enable: true, title: "beetroot", sell: true },
      { position: 6, enable: true, title: "cauliflower", sell: true },
      { position: 7, enable: false, title: "parsnip", sell: false },
      { position: 8, enable: false, title: "radish", sell: false },
      { position: 9, enable: false, title: "wheat", sell: false },
    ],
  forest: [],
  water: [],
}
