{
  crops:
    [
      { position: 0, enable: true, title: "sunflower", planting_time: 60, sell: true },
      { position: 1, enable: true, title: "potato", planting_time: 300, sell: true },
      { position: 2, enable: true, title: "pumpkin", planting_time: 1800, sell: true },
      { position: 3, enable: true, title: "carrot", planting_time: 3600, sell: true },
      { position: 4, enable: true, title: "cabbage", planting_time: 7200, sell: true },
      { position: 5, enable: true, title: "beetroot", planting_time: 14400, sell: true },
      { position: 6, enable: true, title: "cauliflower", planting_time: 28800, sell: true },
      { position: 7, enable: false, title: "parsnip", planting_time: 43200, sell: false },
      { position: 8, enable: false, title: "radish", planting_time: 86400, sell: false },
      { position: 9, enable: false, title: "wheat", planting_time: 86400, sell: false },
    ],
  forest: [],
  water: [],
}
